/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.unicolombo.pb2023.VentanasParaApuestasDP;

import co.edu.unicolombo.pb2023.VentanasParaApuestasDP.Futbols.VentanaParaFutbol11;

/**
 *
 * @author ASUS
 */
public class VentanaParaFutbols extends javax.swing.JDialog {

    /**
     * Creates new form VentanaParaFutbols
     */
    public VentanaParaFutbols(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botonFutbolFreestyle = new javax.swing.JButton();
        botonFutbol11 = new javax.swing.JButton();
        botonFutbolDeSalon = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();
        botonConsultarSaldo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ESCOGE EL TIPO DE FUTBOL DE TU PREFENCIA:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        botonFutbolFreestyle.setBackground(new java.awt.Color(0, 0, 255));
        botonFutbolFreestyle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonFutbolFreestyle.setForeground(new java.awt.Color(255, 255, 255));
        botonFutbolFreestyle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jugadores-de-futbol.png"))); // NOI18N
        botonFutbolFreestyle.setText("FUTBOL FREESTYLE");
        jPanel1.add(botonFutbolFreestyle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 250, -1));

        botonFutbol11.setBackground(new java.awt.Color(0, 0, 255));
        botonFutbol11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonFutbol11.setForeground(new java.awt.Color(255, 255, 255));
        botonFutbol11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estadio.png"))); // NOI18N
        botonFutbol11.setText("FUTBOL 11");
        botonFutbol11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFutbol11ActionPerformed(evt);
            }
        });
        jPanel1.add(botonFutbol11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        botonFutbolDeSalon.setBackground(new java.awt.Color(0, 0, 255));
        botonFutbolDeSalon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonFutbolDeSalon.setForeground(new java.awt.Color(255, 255, 255));
        botonFutbolDeSalon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/campo-de-futbol.png"))); // NOI18N
        botonFutbolDeSalon.setText("FUTBOL DE SALON");
        jPanel1.add(botonFutbolDeSalon, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        botonAtras.setBackground(new java.awt.Color(0, 0, 255));
        botonAtras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back_arrow_14429.png"))); // NOI18N
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(botonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        botonConsultarSaldo.setBackground(new java.awt.Color(0, 0, 255));
        botonConsultarSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/saldo-de-gastos.png"))); // NOI18N
        botonConsultarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultarSaldoActionPerformed(evt);
            }
        });
        jPanel1.add(botonConsultarSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ricardobaccino_dibujo_de_un_leon_gigante_realista_rugiendo_al_a_9f0ae97a-3101-4071-b236-3c63d32f3c0d.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 314));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        // TODO add your handling code here:
        this.dispose();
        VentanaPrincipalParaApuestas_DP ventana = new VentanaPrincipalParaApuestas_DP(null, rootPaneCheckingEnabled);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonConsultarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultarSaldoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        VentanaConsultarSaldoEnV_F saldo = new VentanaConsultarSaldoEnV_F(null, rootPaneCheckingEnabled);
        saldo.setLocationRelativeTo(null);
        saldo.setVisible(true);
    }//GEN-LAST:event_botonConsultarSaldoActionPerformed

    private void botonFutbol11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFutbol11ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        VentanaParaFutbol11 ventana = new VentanaParaFutbol11(null, rootPaneCheckingEnabled);
        ventana.setLocationRelativeTo(null);
        ventana.setVisible(true);
    }//GEN-LAST:event_botonFutbol11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaParaFutbols.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaParaFutbols.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaParaFutbols.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaParaFutbols.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaParaFutbols dialog = new VentanaParaFutbols(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonConsultarSaldo;
    private javax.swing.JButton botonFutbol11;
    private javax.swing.JButton botonFutbolDeSalon;
    private javax.swing.JButton botonFutbolFreestyle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
