package co.edu.unicolombo.pb2023.Ventanas;

import co.edu.unicolombo.pb2023.Datos.Usuario;
import co.edu.unicolombo.pb2023.VentanasDeRecargar_RetirarSaldos.VentanaRecargarSaldo;
import co.edu.unicolombo.pb2023.VentanasDeRecargar_RetirarSaldos.VentanaRetirarSaldo;
import co.edu.unicolombo.pb2023.VentanasDeRecargar_RetirarSaldos.VentanaConsultarSaldo;
import co.edu.unicolombo.pb2023.VentanasDeRecargar_RetirarSaldos.VentanaReportePorRecarga;
import co.edu.unicolombo.pb2023.VentanasDeRecargar_RetirarSaldos.VentanaReportePorRetiro;
import co.edu.unicolombo.pb2023.VentanasParaApuestasDP.VentanaPrincipalParaApuestas_DP;

import javax.swing.JOptionPane;

public class VentanaSegunda extends javax.swing.JFrame {
    /**
     * Creates new form VentanaPrincipalParaApuestas_DP
     */
    public VentanaSegunda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        barraMenus = new javax.swing.JMenuBar();
        menuInicio = new javax.swing.JMenu();
        itemIniciarSecion1 = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        itemConsultarUsuario = new javax.swing.JMenuItem();
        itemEditarDatos = new javax.swing.JMenuItem();
        itemEliminarme = new javax.swing.JMenuItem();
        menuReportesUsuarios = new javax.swing.JMenu();
        itemReporteTodos = new javax.swing.JMenuItem();
        itemPorNombre = new javax.swing.JMenuItem();
        itemPorCorreo = new javax.swing.JMenuItem();
        itemPorTelefono = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuApuestas = new javax.swing.JMenu();
        itemApuestasAbiertas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemRecargarSaldo = new javax.swing.JMenuItem();
        itemRetirarSaldo = new javax.swing.JMenuItem();
        itenConsultarsaldo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        itemReportePorRecarga = new javax.swing.JMenuItem();
        itenReportePrRetiro = new javax.swing.JMenuItem();
        menuCerrarsesion = new javax.swing.JMenu();
        itemCerrar = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        ItemAyuda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APP DE APUESTAS DEPORTIVAS\n");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("BIENVENIDO A SPORTSBETS360 FMK");
        titulo.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(486, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(titulo)
                .addContainerGap(409, Short.MAX_VALUE))
        );

        barraMenus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        menuInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/homepage_home_house_icon_153873.png"))); // NOI18N
        menuInicio.setText("Inicio");

        itemIniciarSecion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/account_login_log_in_icon_250759.png"))); // NOI18N
        itemIniciarSecion1.setText("Iniciar Secion...");
        itemIniciarSecion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIniciarSecion1ActionPerformed(evt);
            }
        });
        menuInicio.add(itemIniciarSecion1);

        barraMenus.add(menuInicio);

        menuUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user_person_people_6100.png"))); // NOI18N
        menuUsuarios.setText("Mi cuenta");

        itemConsultarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/find_search_card_user_16713 (1).png"))); // NOI18N
        itemConsultarUsuario.setText("Consultar mis datos...");
        itemConsultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemConsultarUsuario);

        itemEditarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/businessapplication_edit_male_user_thepencil_theclient_negocio_2321 (1).png"))); // NOI18N
        itemEditarDatos.setText("Editar mis datos...");
        itemEditarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarDatosActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemEditarDatos);

        itemEliminarme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete_delete_deleteusers_delete_male_user_maleclient_2348.png"))); // NOI18N
        itemEliminarme.setText("Eliminarme...");
        itemEliminarme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEliminarmeActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemEliminarme);

        menuReportesUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/userreviews_usuario_12980.png"))); // NOI18N
        menuReportesUsuarios.setText("Resportes...");

        itemReporteTodos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/userreviews_usuario_12980.png"))); // NOI18N
        itemReporteTodos.setText("Todos...");
        itemReporteTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReporteTodosActionPerformed(evt);
            }
        });
        menuReportesUsuarios.add(itemReporteTodos);

        itemPorNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/userreviews_usuario_12980.png"))); // NOI18N
        itemPorNombre.setText("Por nombre...");
        itemPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPorNombreActionPerformed(evt);
            }
        });
        menuReportesUsuarios.add(itemPorNombre);

        itemPorCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/userreviews_usuario_12980.png"))); // NOI18N
        itemPorCorreo.setText("Por correo...");
        itemPorCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPorCorreoActionPerformed(evt);
            }
        });
        menuReportesUsuarios.add(itemPorCorreo);

        itemPorTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/userreviews_usuario_12980.png"))); // NOI18N
        itemPorTelefono.setText("Por telefono");
        itemPorTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPorTelefonoActionPerformed(evt);
            }
        });
        menuReportesUsuarios.add(itemPorTelefono);

        menuUsuarios.add(menuReportesUsuarios);

        barraMenus.add(menuUsuarios);

        jMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/data_all_icon_155544.png"))); // NOI18N
        jMenu1.setText("Deportes");

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/playsoccersports_juegos_futbo_1762.png"))); // NOI18N
        jMenu2.setText("Futbol...");

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/campo-de-futbol.png"))); // NOI18N
        jMenuItem7.setText("Futbol de salon...");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jugadores-de-futbol.png"))); // NOI18N
        jMenuItem8.setText("Futbol Freestyle...");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estadio.png"))); // NOI18N
        jMenuItem9.setText("Futbol 11...");
        jMenu2.add(jMenuItem9);

        jMenu1.add(jMenu2);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/jugador-de-voleibol.png"))); // NOI18N
        jMenuItem1.setText("Voleibol...");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/baloncesto.png"))); // NOI18N
        jMenuItem2.setText("Baloncesto...");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tenis.png"))); // NOI18N
        jMenuItem3.setText("Tenis...");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/corredor.png"))); // NOI18N
        jMenuItem4.setText("Atletismo...");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ciclismo.png"))); // NOI18N
        jMenuItem5.setText("Ciclismo...");
        jMenu1.add(jMenuItem5);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guantes-de-boxeo.png"))); // NOI18N
        jMenuItem6.setText("Boxeo...");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        barraMenus.add(jMenu1);

        menuApuestas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuApuestas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cash_icon-icons.com_51090.png"))); // NOI18N
        menuApuestas.setText("Apuestas Abiertas");

        itemApuestasAbiertas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/apuesta.png"))); // NOI18N
        itemApuestasAbiertas.setText("Apuestas...");
        itemApuestasAbiertas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemApuestasAbiertasActionPerformed(evt);
            }
        });
        menuApuestas.add(itemApuestasAbiertas);

        barraMenus.add(menuApuestas);

        jMenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/recargar.png"))); // NOI18N
        jMenu3.setText("Recargas y Retiros");

        itemRecargarSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reembolso.png"))); // NOI18N
        itemRecargarSaldo.setText("Recargas Saldo...");
        itemRecargarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRecargarSaldoActionPerformed(evt);
            }
        });
        jMenu3.add(itemRecargarSaldo);

        itemRetirarSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/retiro-de-efectivo.png"))); // NOI18N
        itemRetirarSaldo.setText("Retirar Saldo...");
        itemRetirarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRetirarSaldoActionPerformed(evt);
            }
        });
        jMenu3.add(itemRetirarSaldo);

        itenConsultarsaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/saldo-de-gastos.png"))); // NOI18N
        itenConsultarsaldo.setText("Consultar mi saldo...");
        itenConsultarsaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itenConsultarsaldoActionPerformed(evt);
            }
        });
        jMenu3.add(itenConsultarsaldo);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte.png"))); // NOI18N
        jMenu4.setText("Reportes...");

        itemReportePorRecarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte.png"))); // NOI18N
        itemReportePorRecarga.setText("Por recarga...");
        itemReportePorRecarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReportePorRecargaActionPerformed(evt);
            }
        });
        jMenu4.add(itemReportePorRecarga);

        itenReportePrRetiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reporte.png"))); // NOI18N
        itenReportePrRetiro.setText("Por retiro...");
        itenReportePrRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itenReportePrRetiroActionPerformed(evt);
            }
        });
        jMenu4.add(itenReportePrRetiro);

        jMenu3.add(jMenu4);

        barraMenus.add(jMenu3);

        menuCerrarsesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuCerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/close_12890.png"))); // NOI18N
        menuCerrarsesion.setText("Cerrar sesion");

        itemCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arrow_logout_exit_close_cancel_icon_208165.png"))); // NOI18N
        itemCerrar.setText("Cerrar...");
        itemCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCerrarActionPerformed(evt);
            }
        });
        menuCerrarsesion.add(itemCerrar);

        barraMenus.add(menuCerrarsesion);

        menuAyuda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/help_question_1566.png"))); // NOI18N
        menuAyuda.setText("Ayuda");

        ItemAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/acceso.png"))); // NOI18N
        ItemAyuda.setText("Entrar...");
        ItemAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemAyudaActionPerformed(evt);
            }
        });
        menuAyuda.add(ItemAyuda);

        barraMenus.add(menuAyuda);

        setJMenuBar(barraMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarUsuarioActionPerformed
        VentanaMiCuenta consultar = new VentanaMiCuenta(this, rootPaneCheckingEnabled);
        consultar.setLocationRelativeTo(null);
        consultar.setVisible(true);
    }//GEN-LAST:event_itemConsultarUsuarioActionPerformed

    private void itemEditarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarDatosActionPerformed
        // TODO add your handling code here:
        itemConsultarUsuarioActionPerformed(evt);
    }//GEN-LAST:event_itemEditarDatosActionPerformed

    private void itemEliminarmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEliminarmeActionPerformed
        // TODO add your handling code here:
         itemConsultarUsuarioActionPerformed(evt);

    }//GEN-LAST:event_itemEliminarmeActionPerformed

    private void itemReporteTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReporteTodosActionPerformed
        if (Usuario.usuariosBD == null || Usuario.usuariosBD.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No existe un Usuario en el sistema", "Resultado Negatico", JOptionPane.WARNING_MESSAGE);
            return;
        }
        VentanaReportesUsuarios ventana3 = new VentanaReportesUsuarios(this, rootPaneCheckingEnabled);
        ventana3.setLocationRelativeTo(null);
        ventana3.setVisible(true );
    }//GEN-LAST:event_itemReporteTodosActionPerformed

    private void itemPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPorNombreActionPerformed
        // TODO add your handling code here:
        if (Usuario.usuariosBD == null || Usuario.usuariosBD.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No existe un Usuario en el sistema", "Resultado Negatico", JOptionPane.WARNING_MESSAGE);
            return;
        }
        VentanaReportesNombres ventana4 = new VentanaReportesNombres(this, rootPaneCheckingEnabled);
        ventana4.setLocationRelativeTo(null);
        ventana4.setVisible(true);
    }//GEN-LAST:event_itemPorNombreActionPerformed

    private void itemPorCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPorCorreoActionPerformed
        // TODO add your handling code here:
        if (Usuario.usuariosBD == null || Usuario.usuariosBD.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No existe un Usuario en el sistema", "Resultado Negatico", JOptionPane.WARNING_MESSAGE);
            return;
        }
        VentanaReportesCorreo ventana5 = new VentanaReportesCorreo(this, rootPaneCheckingEnabled);
        ventana5.setLocationRelativeTo(null);
        ventana5.setVisible(true);
    }//GEN-LAST:event_itemPorCorreoActionPerformed

    private void itemPorTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPorTelefonoActionPerformed
        // TODO add your handling code here:
        if (Usuario.usuariosBD == null || Usuario.usuariosBD.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No existe un Usuario en el sistema", "Resultado Negatico", JOptionPane.WARNING_MESSAGE);
            return;
        }
        VentanaReportesTelefono ventana6 = new VentanaReportesTelefono(this, rootPaneCheckingEnabled);
        ventana6.setLocationRelativeTo(null);
        ventana6.setVisible(true);
    }//GEN-LAST:event_itemPorTelefonoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened
    private void itemIniciarSecion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIniciarSecion1ActionPerformed
        // TODO add your handling code here:
        VentanaInicioSecion inicio = new VentanaInicioSecion(this, rootPaneCheckingEnabled);
        inicio.setLocationRelativeTo(null);
        inicio.setVisible(true); 
    }//GEN-LAST:event_itemIniciarSecion1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void itemCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCerrarActionPerformed
        // TODO add your handling code here:
        VentanaSegunda.this.dispose();
        JOptionPane.showMessageDialog(null, "La sesión fue cerrada correctamente, gracias por entrar a nuestras instalaciones.");
        VentanaInicioSecion inicio = new VentanaInicioSecion(this, rootPaneCheckingEnabled);
        inicio.setLocationRelativeTo(null);
        inicio.setVisible(true); 
        VentanaSegunda.this.dispose();
 
    }//GEN-LAST:event_itemCerrarActionPerformed

    private void itemRecargarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRecargarSaldoActionPerformed
        // TODO add your handling code here:
        VentanaRecargarSaldo recargar = new VentanaRecargarSaldo(this, rootPaneCheckingEnabled);
        recargar.setLocationRelativeTo(null);
        recargar.setVisible(true);
    }//GEN-LAST:event_itemRecargarSaldoActionPerformed

    private void itemRetirarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRetirarSaldoActionPerformed
        // TODO add your handling code here:
        VentanaRetirarSaldo retirar = new VentanaRetirarSaldo(this, rootPaneCheckingEnabled);
        retirar.setLocationRelativeTo(null);
        retirar.setVisible(true);
    }//GEN-LAST:event_itemRetirarSaldoActionPerformed

    private void itenConsultarsaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itenConsultarsaldoActionPerformed
        // TODO add your handling code here:
        VentanaConsultarSaldo saldo = new VentanaConsultarSaldo(this, rootPaneCheckingEnabled);
        saldo.setLocationRelativeTo(null);
        saldo.setVisible(true);
    }//GEN-LAST:event_itenConsultarsaldoActionPerformed

    private void itenReportePrRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itenReportePrRetiroActionPerformed
        // TODO add your handling code here:
        VentanaReportePorRetiro reporte = new VentanaReportePorRetiro(this, rootPaneCheckingEnabled);
        reporte.setLocationRelativeTo(null);
        reporte.setVisible(true);
    }//GEN-LAST:event_itenReportePrRetiroActionPerformed

    private void itemReportePorRecargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReportePorRecargaActionPerformed
        // TODO add your handling code here:
        VentanaReportePorRecarga recarga = new VentanaReportePorRecarga(this, rootPaneCheckingEnabled);
        recarga.setLocationRelativeTo(null);
        recarga.setVisible(true);
    }//GEN-LAST:event_itemReportePorRecargaActionPerformed

    private void ItemAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemAyudaActionPerformed
        // TODO add your handling code here:
        VentanaAyuda ayuda = new VentanaAyuda(this, rootPaneCheckingEnabled);
        ayuda.setLocationRelativeTo(null);
        ayuda.setVisible(true);   
    }//GEN-LAST:event_ItemAyudaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void itemApuestasAbiertasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemApuestasAbiertasActionPerformed
        // TODO add your handling code here:
        VentanaPrincipalParaApuestas_DP apuestas = new VentanaPrincipalParaApuestas_DP(this, rootPaneCheckingEnabled);
        apuestas.setLocationRelativeTo(null);
        apuestas.setVisible(true);
    }//GEN-LAST:event_itemApuestasAbiertasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSegunda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSegunda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSegunda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSegunda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSegunda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemAyuda;
    private javax.swing.JMenuBar barraMenus;
    private javax.swing.JMenuItem itemApuestasAbiertas;
    private javax.swing.JMenuItem itemCerrar;
    private javax.swing.JMenuItem itemConsultarUsuario;
    private javax.swing.JMenuItem itemEditarDatos;
    private javax.swing.JMenuItem itemEliminarme;
    private javax.swing.JMenuItem itemIniciarSecion1;
    private javax.swing.JMenuItem itemPorCorreo;
    private javax.swing.JMenuItem itemPorNombre;
    private javax.swing.JMenuItem itemPorTelefono;
    private javax.swing.JMenuItem itemRecargarSaldo;
    private javax.swing.JMenuItem itemReportePorRecarga;
    private javax.swing.JMenuItem itemReporteTodos;
    private javax.swing.JMenuItem itemRetirarSaldo;
    private javax.swing.JMenuItem itenConsultarsaldo;
    private javax.swing.JMenuItem itenReportePrRetiro;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuApuestas;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuCerrarsesion;
    private javax.swing.JMenu menuInicio;
    private javax.swing.JMenu menuReportesUsuarios;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
