/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.unicolombo.pb2023.Ventanas;

import co.edu.unicolombo.pb2023.Datos.Usuario;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class VentanaMiCuenta extends javax.swing.JDialog {

    /**
     * Creates new form VentanaConsultarUsuarios
     */
    public VentanaMiCuenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtApellidoUsuario = new javax.swing.JTextField();
        txtDocumentoUsuario = new javax.swing.JTextField();
        txtCorreoUsuario = new javax.swing.JTextField();
        txtTelefonoUsuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtContraseñaUsuario = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btonCancelar = new javax.swing.JButton();
        botonBuscar = new javax.swing.JButton();
        botonEditar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Datos de Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Apellidos:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Documento:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Telefono:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Correo:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Contraseña");

        txtContraseñaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                    .addComponent(txtApellidoUsuario)
                    .addComponent(txtDocumentoUsuario)
                    .addComponent(txtTelefonoUsuario)
                    .addComponent(txtCorreoUsuario)
                    .addComponent(txtContraseñaUsuario))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtApellidoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocumentoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTelefonoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCorreoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtContraseñaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/addusergroup_1251.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("FORMULARIO PARA GESTIONAR USUARIOS");

        btonCancelar.setBackground(new java.awt.Color(0, 0, 204));
        btonCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/arrow_logout_exit_close_cancel_icon_208165.png"))); // NOI18N
        btonCancelar.setText("Cancelar");
        btonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonCancelarActionPerformed(evt);
            }
        });

        botonBuscar.setBackground(new java.awt.Color(0, 0, 204));
        botonBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/find_search_card_user_16713 (1).png"))); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonEditar.setBackground(new java.awt.Color(0, 0, 204));
        botonEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonEditar.setForeground(new java.awt.Color(255, 255, 255));
        botonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/businessapplication_edit_male_user_thepencil_theclient_negocio_2321 (1).png"))); // NOI18N
        botonEditar.setText("Editar");
        botonEditar.setAutoscrolls(true);
        botonEditar.setBorderPainted(false);
        botonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarActionPerformed(evt);
            }
        });

        botonEliminar.setBackground(new java.awt.Color(0, 0, 204));
        botonEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonEliminar.setForeground(new java.awt.Color(255, 255, 255));
        botonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete_delete_deleteusers_delete_male_user_maleclient_2348.png"))); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonAtras.setBackground(new java.awt.Color(0, 0, 204));
        botonAtras.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonAtras.setForeground(new java.awt.Color(255, 255, 255));
        botonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back_arrow_14429.png"))); // NOI18N
        botonAtras.setText("Atras");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonAtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btonCancelar)
                                .addGap(53, 53, 53)
                                .addComponent(botonEliminar)
                                .addGap(59, 59, 59)
                                .addComponent(botonEditar)
                                .addGap(45, 45, 45)
                                .addComponent(botonBuscar)))
                        .addGap(37, 37, 37))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btonCancelar)
                            .addComponent(botonBuscar)
                            .addComponent(botonEditar)
                            .addComponent(botonEliminar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonAtras)
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContraseñaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaUsuarioActionPerformed

    private void btonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonCancelarActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null, "¿Desea cerrar la ventana?", "OJO - CONFIRMAR"
            , JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opcion == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btonCancelarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        // Recuperar el Correo del formulario
        String correo = txtCorreoUsuario.getText();
        
        // Verificamos si el campo de Correo está vacío
        if (correo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese el correo del Usuario a consultar, antes presionar el Boton buscar.");
            return;
        }
        
        // Verificamos si la Base de Datos esta llena o esta vacio
        if (Usuario.usuariosBD == null || Usuario.usuariosBD.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No existen Usuarios en la Base de Datos");
        }else{
            
            // Buscamos en Usuario en el diccionario apartir del Correo
            if (Usuario.usuariosBD.containsKey(correo)) {
                Usuario usuarios = Usuario.usuariosBD.get(correo);
                txtNombreUsuario.setText(usuarios.nombre);
                txtApellidoUsuario.setText(usuarios.apellidos);
                txtDocumentoUsuario.setText(usuarios.documento);
                txtTelefonoUsuario.setText(usuarios.telefono);
                txtCorreoUsuario.setText(usuarios.correo);
                txtContraseñaUsuario.setText(usuarios.contraseña);
            }else{
                JOptionPane.showMessageDialog(null, "No existe un Usuario con ese Correo en la Base de Datos");
                txtNombreUsuario.setText("");
                txtApellidoUsuario.setText("");
                txtDocumentoUsuario.setText("");
                txtTelefonoUsuario.setText("");
                txtCorreoUsuario.setText("");
                txtContraseñaUsuario.setText("");
                
            }
            
        }
        
    }//GEN-LAST:event_botonBuscarActionPerformed
    private boolean seEditaronDatos() {
        
        // Obtén los valores actuales del usuario del diccionario según el Correo
        Usuario usuarioActual = Usuario.usuariosBD.get(txtCorreoUsuario.getText());

        // Compara los valores actuales con los valores ingresados en el formulario
        String nombreActual = usuarioActual.nombre;
        String apellidoActual = usuarioActual.apellidos;
        String documentoActual = usuarioActual.documento;
        String telefonoActual = usuarioActual.telefono;
        char[] contraseñaActual = usuarioActual.contraseña.toCharArray();

        String nombreFormulario = txtNombreUsuario.getText();
        String apellidoFormulario = txtApellidoUsuario.getText();
        String telefonoFormulario = txtTelefonoUsuario.getText();
        String documentoFormulario = txtDocumentoUsuario.getText();
        char[] contraseñaFormulario = txtContraseñaUsuario.getPassword();

        boolean datosEditados = !nombreActual.equals(nombreFormulario) ||
                               !apellidoActual.equals(apellidoFormulario) ||
                               !telefonoActual.equals(telefonoFormulario) ||
                               !documentoActual.equals(documentoFormulario) ||
                               !Arrays.equals(contraseñaActual, contraseñaFormulario);

        return datosEditados;
    }
    private void botonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarActionPerformed
        // botonBuscarActionPerformed(evt);
        if (!seEditaronDatos()) {
            JOptionPane.showMessageDialog(null, "No editaste ningún dato.");
            return;
        }
        
        // Validamos que el campo Correo tenga algun dato
        if (txtCorreoUsuario.getText() == null || txtCorreoUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Para editar primero debe guardar y luego buscar un Usuario");
            txtNombreUsuario.setText("");
            txtApellidoUsuario.setText("");
            txtDocumentoUsuario.setText("");
            txtTelefonoUsuario.setText("");
            txtCorreoUsuario.setText("");
            txtContraseñaUsuario.setText("");
            return;
        }
        
        // Obtenemos los datos del Usuario de este Diccionario apartir del Correo
        Usuario usuarios = Usuario.usuariosBD.get(txtCorreoUsuario.getText());
        // Verificar si el usuario existe en el diccionario
        if (Usuario.usuariosBD == null || Usuario.usuariosBD.isEmpty()) {
            JOptionPane.showMessageDialog(null, "El usuario con el Correo especificado no existe.");
            return;
        }
         
        // Obtenemos las datos ingesados desde el formulario
        String nombres = txtNombreUsuario.getText();
        String apellidos = txtApellidoUsuario.getText();
        String telefono = txtTelefonoUsuario.getText();
        String documento = txtDocumentoUsuario.getText();
        char[] contraseña = txtContraseñaUsuario.getPassword();
        
        // Verifico la longitud de los campos
        if (nombres.length() > 255) {
            JOptionPane.showMessageDialog(null, "El nombre no puede superar los 255 caracteres.");
            txtNombreUsuario.setText("");
        } else if (apellidos.length() > 255) {
            JOptionPane.showMessageDialog(null, "El apellido no puede superar los 255 caracteres.");
            txtApellidoUsuario.setText("");
        } else if (documento.length() > 20) { // Limito el documento a 20 caracteres
            JOptionPane.showMessageDialog(null, "El número de documento no puede superar los 20 caracteres.");
            txtDocumentoUsuario.setText("");
        } else if (!telefono.matches("\\d{7,}") || telefono.length() > 15) {
            JOptionPane.showMessageDialog(null, "El número de teléfono debe ser numérico y tener entre 7 y 15 caracteres.");
            txtTelefonoUsuario.setText("");
        } else if (nombres.isEmpty() || apellidos.isEmpty() || documento.isEmpty() ||
                   telefono.isEmpty() || contraseña.length == 0) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos antes de editar la información.");
        } else {
            
        // Canbiarle los datos al Usuario por los datos ingresados en el formulario
        usuarios.nombre = nombres;
        usuarios.apellidos = apellidos;
        usuarios.telefono = telefono;
        usuarios.documento = documento;
        String clave = String.valueOf(contraseña);
        usuarios.contraseña = clave;
        
        // Mostrar mensaje
        Usuario.usuariosBD.put(usuarios.correo, usuarios);
        JOptionPane.showMessageDialog(null, "Datos del Usuario modificados con exito");
        txtNombreUsuario.setText("");
        txtApellidoUsuario.setText("");
        txtDocumentoUsuario.setText("");
        txtTelefonoUsuario.setText("");
        txtCorreoUsuario.setText("");
        txtContraseñaUsuario.setText("");
        
        }
        
    }//GEN-LAST:event_botonEditarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // Validamos que el campo Correo tenga algun dato
        if (txtCorreoUsuario.getText() == null || txtCorreoUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Para eliminar primero debe Registrarse y luego buscar un Usuario");
            txtNombreUsuario.setText("");
            txtApellidoUsuario.setText("");
            txtDocumentoUsuario.setText("");
            txtTelefonoUsuario.setText("");
            txtCorreoUsuario.setText("");
            txtContraseñaUsuario.setText("");
            return;
        }
        // Obtenemos los datos del Usuario de este Diccionario apartir del Correo
        Usuario usuarios = Usuario.usuariosBD.get(txtCorreoUsuario.getText());
        
        // Verificar si el usuario existe en el diccionario
        if (usuarios == null) {
            JOptionPane.showMessageDialog(null, "El usuario con el Correo especificado no existe.");
            return;
        }
        
        int opcion = JOptionPane.showConfirmDialog(null, "¿Seguro deseas elimimar este Usuario?", "OJO - CONFIRMAR"
            , JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (opcion == JOptionPane.YES_OPTION) {
            Usuario.usuariosBD.remove(txtCorreoUsuario.getText());
            int total = Usuario.usuariosBD.size();
            JOptionPane.showMessageDialog(null, "Usuario eliminado con exito\nTOTAL: " + total);
        }
        
        txtNombreUsuario.setText("");
        txtApellidoUsuario.setText("");
        txtDocumentoUsuario.setText("");
        txtTelefonoUsuario.setText("");
        txtCorreoUsuario.setText("");
        txtContraseñaUsuario.setText("");
        
    }//GEN-LAST:event_botonEliminarActionPerformed

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        VentanaSegunda ventana2 = new VentanaSegunda();
        ventana2.setLocationRelativeTo(null);
        ventana2.setExtendedState(VentanaSegunda.MAXIMIZED_BOTH);
        ventana2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMiCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMiCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMiCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMiCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaMiCuenta dialog = new VentanaMiCuenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonEditar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton btonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtApellidoUsuario;
    private javax.swing.JPasswordField txtContraseñaUsuario;
    private javax.swing.JTextField txtCorreoUsuario;
    private javax.swing.JTextField txtDocumentoUsuario;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtTelefonoUsuario;
    // End of variables declaration//GEN-END:variables

   
}
